Rwa 2369
hmcts/wa-standalone-task-bpmn pull request #198
Opened 2023-05-02 14:37 UTC by kvvasudev

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-2369

### Change description ###

Upgrade to spring-boot 3

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-05-23 10:46 UTC, rafalkalita commented on src/integrationTest/java/uk/gov/hmcts/reform/wastandalonetaskbpmn/config/OpenAPIPublisherTest.java
> +@Disabled
Why do we need to disable this test?

2023-05-23 14:46 UTC, rafalkalita approved these changes

2023-05-23 19:45 UTC, rafalkalita requested changes

2023-05-23 19:45 UTC, rafalkalita commented on .github/workflows/publish-openapi.yaml
> +      test_to_run: 'uk.gov.hmcts.reform.demo.openapi.OpenAPIPublisherTest'
```suggestion
      test_to_run: 'uk.gov.hmcts.reform.wastandalonetaskbpmn.config.OpenAPIPublisherTest'
```

2023-05-24 10:37 UTC, rafalkalita submitted a review, later dismissed

2023-05-24 10:44 UTC, kvvasudev commented on src/integrationTest/java/uk/gov/hmcts/reform/wastandalonetaskbpmn/config/OpenAPIPublisherTest.java
> +@Disabled
Enabled it now. Thank you.

2023-06-01 12:59 UTC, rafalkalita approved these changes

2023-06-01 13:11 UTC, merged