Added camunda deployment script
hmcts/wa-standalone-task-bpmn pull request #28
Opened 2020-12-04 14:33 UTC by lewis150193

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-254

### Change description ###
Added script for automated bpmn and dmn deployment

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2020-12-04 14:42 UTC, iguannago commented on scripts/camunda-deployment.sh
> +AUTHORIZATION= sh ./idam-service-token.sh
we have this script already in the /actions folder

2020-12-04 14:42 UTC, iguannago commented on scripts/idam-service-token.sh
> +#!/bin/bash
I think this is a duplicate

2020-12-14 11:37 UTC, iguannago submitted a review, later dismissed

2020-12-15 11:10 UTC, BenNzewi commented on README.md
> + * `WA_BPMNS_DMNS_PATH` - to the path where you WA BPMNS are stored. [Link to path here](https://github.com/hmcts/wa-standalone-task-bpmn/tree/master/src/main/resources)
small typo; where you WA BPMNS should be where you**r** WA BPMNS

2020-12-15 11:11 UTC, BenNzewi commented on README.md
> + * `IA_TASK_DMNS_BPMNS_PATH` - to the path where DMS in `IA_TASK_CONFIGURATION` are stored. [Link to path here](https://github.com/hmcts/ia-task-configuration/tree/master/src/main/resources)
small typo; to the path where DMS should be to the path where DM**N**S

2020-12-15 15:53 UTC, alexbaeza approved these changes

2020-12-15 15:54 UTC, alexbaeza requested changes

2020-12-15 15:54 UTC, alexbaeza commented on README.md
> +
don't need this in this repo

2020-12-15 16:45 UTC, alexbaeza approved these changes

2020-12-15 16:50 UTC, merged